---
- hosts: 
    - webservers
    - testservers
  remote_user: vagrant
  become: yes
  roles:
    - apache

- hosts: 
    - dbservers
    - testservers
  remote_user: vagrant
  become: yes
  roles:
    - postgresql
