---
- hosts: webservers
  remote_user: vagrant
  roles:
    - apache

- hosts: dbservers
  remote_user: vagrant
  roles:
    - mysql

- hosts: testserver
  remote_user: vagrant
  roles:
    - apache
    - mysql
