---
- hosts: webservers
  remote_user: vagrant
  become: yes
  roles:
    - apache

- hosts: dbservers
  remote_user: vagrant
  become: yes
  roles:
    - postgresql

- hosts: testservers
  remote_user: vagrant
  become: yes
  roles:
    - apache
    - postgresql
